# Generated by Django 3.1.4 on 2021-02-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetflixUser',
        ),
    ]
