# Generated by Django 3.1.4 on 2021-02-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0003_remove_nfuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
