# Generated by Django 3.1.4 on 2021-02-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0004_nfuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfuser',
            name='username',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
